CREATE TABLE public.quiz_attempt_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id UUID NOT NULL REFERENCES public.quiz_attempts(id) ON DELETE CASCADE,
  question_id UUID NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(attempt_id, question_id)
);

ALTER TABLE public.quiz_attempt_questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for users based on attempt ownership" 
ON public.quiz_attempt_questions FOR SELECT 
USING (auth.uid() = (SELECT user_id FROM public.quiz_attempts WHERE id = attempt_id));
